import turtle

turtle.width(10)
turtle.color("red")
turtle.begin_fill()
turtle.circle(steps = 6 ,radius = 90)
turtle.end_fill()

turtle.hideturtle()
turtle.showturtle()
turtle.color("white")
turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.color("black")
turtle.right(180)
turtle.forward(20)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.left(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.color("white")
turtle.write("STOP", font = ("Times", 40, "bold"))
turtle.hideturtle()

turtle.done()